#!/bin/bash

set -euo pipefail

bash_source="${BASH_SOURCE[0]}"
while [[ -L "${bash_source}" ]]; do
  bash_dir="$(cd -P "$(dirname "${bash_source}")" && pwd)"
  bash_source="$(readlink "${bash_source}")"
  [[ "${bash_source}" != /* ]] && bash_source="${bash_dir}/${bash_source}"
done
readonly dir="$(cd -P "$(dirname "${bash_source}")" && pwd)"

pushd "${dir}/../" >/dev/null
trap 'popd >/dev/null' exit

for ip in $(lxc list '^kubedee-.*-worker-.*$' --format json | jq -r ".[].state.network.eth0.addresses[] | select(.family == \"inet\").address"); do
  sudo route add -net 10.32.0.0/16 gw "${ip}" && break
done
