#!/bin/bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <k8s version> <dest dir>" >&2
  exit 1
fi

readonly k8s_version="${1}"
readonly dest_dir="${2}"

mkdir -p "${dest_dir}"
(
  cd "${dest_dir}"
  curl -LO "https://dl.k8s.io/${k8s_version}/kubernetes-server-linux-amd64.tar.gz"
  tar -xvf "kubernetes-server-linux-amd64.tar.gz" \
    "kubernetes/server/bin/"{kube-apiserver,kube-controller-manager,kubectl,kubelet,kube-proxy,kube-scheduler}
  rm -f "kubernetes-server-linux-amd64.tar.gz"
)
