#!/bin/bash

set -euo pipefail

bash_source="${BASH_SOURCE[0]}"
while [[ -L "${bash_source}" ]]; do
  bash_dir="$(cd -P "$(dirname "${bash_source}")" && pwd)"
  bash_source="$(readlink "${bash_source}")"
  [[ "${bash_source}" != /* ]] && bash_source="${bash_dir}/${bash_source}"
done
readonly dir="$(cd -P "$(dirname "${bash_source}")" && pwd)"

pushd "${dir}/../" >/dev/null
trap 'popd >/dev/null' exit

kubectl apply -f manifests/nginx.yaml

readonly service_ip="$(kubectl get services -o jsonpath='{.items[?(@.metadata.name=="nginx")].spec.clusterIP}')"
readonly service_port="$(kubectl get services -o jsonpath='{.items[?(@.metadata.name=="nginx")].spec.ports[0].port}')"

until curl -s --max-time 2 "http://${service_ip}:${service_port}"; do
  echo "waiting for nginx service to come up"
  sleep 1
done

kubectl delete -f manifests/nginx.yaml
